### ISSUE TITLE
Adding a bot as a Team member - (bots in channels) NOT working

### ISSUE THREAD

**Issue by nycodes9** [RichMoeMSFT/TeamsTestBot#1]
I was successfully able to add(sideload) a 1:1 bot and interact but instruction outlined here recently - [Bots in channels](https://msdn.microsoft.com/en-us/microsoft-teams/botsadd#adding-a-bot-as-a-team-member---bots-in-channels) is not working (the bot doesn't show up for add member in teams)

**Comment by RichMoeMSFT** [comment]
@nycodes9 See updated documentation here:  https://msdn.microsoft.com/en-us/microsoft-teams/sideload
