### ISSUE TITLE
Teams bot not receiving messages

### ISSUE THREAD

**Issue by wslyvh** [RichMoeMSFT/TeamsTestBot#5]
Not sure if it's really an issue, but there seems to be no way to get all messages within a channel.
Only if you mention the bot specifically or start a 1-on-1 conversation.

Is that correct or am I missing something?

**Comment by RichMoeMSFT** [comment]
That is by design.  Bots only hear messages in channels if they are @mentioned.  We are looking at options to allow bots to eavesdrop on, but there are obvious security/privacy issues that need to be resolved before we can open up a feature like that.

**Comment by wslyvh** [comment]
Thanks for the quick reply. Makes sense.
Any other way (for statistical purposes) to read all messages in a channel? 
Like mentioning and reading (part of) the history channel?
